name: VineriumLib
version: 1.0
author: SaintQd
main: org.saintqd.vineriumlib.VineriumLib
api-version: 1.21.8
softdepend:
  - Vault
  - PlaceholderAPI
  - DiscordSRV
permissions:
  vineriumlib.admin:
    description: Access to admin commands.
    default: op